### PR TITLE
Fix bug when an empty response is returned when listing topics

### PR DESCRIPTION
**Pull request by allenporter**

### CODE REVIEW

**Comment by rednebmas** [comment]
For anyone else who ends up here, and is blocked until the update goes through, a workaround is to just add a "test" topic here https://console.cloud.google.com/cloudpubsub/topic/list

**Comment by rednebmas** [comment]
Hm. Now I'm getting the error

```
Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 10:59:58 PM (2 occurrences)
Last logged: 11:01:22 PM

Error setting up entry 413 for nest
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/nest/__init__.py", line 220, in async_setup_entry
    subscriber = await api.new_subscriber(hass, entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/nest/api.py", line 118, in new_subscriber
    CONF_SUBSCRIPTION_NAME, entry.data[CONF_SUBSCRIBER_ID]
                            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'subscriber_id'
```

@allenporter, any idea?

**Comment by rednebmas** [comment]
Ok, I manually edited the `config/.storage/core.config_entries` file to add a `subscriber_id ` key at the same level as the `subscription_name` with the name of the subscription which looks like `projects/sams-gcp-project-name/subscriptions/XXXXXXXXXXX`. Finally working!

**Comment by allenporter** [comment]
Can you post an issue in home assistant repo please rather than chiming into PRs randomly?

**Comment by lpw96** [comment]
> Ok, I manually edited the `config/.storage/core.config_entries` file to add a `subscriber_id ` key at the same level as the `subscription_name` with the name of the subscription which looks like `projects/sams-gcp-project-name/subscriptions/XXXXXXXXXXX`. Finally working!

Are you able to elaborate on what you have done here please?
I have limited knowledge and desperately trying to make this work but don't quite understand.

**Comment by allenporter** [comment]
> Are you able to elaborate on what you have done here please? I have limited knowledge and desperately trying to make this work but don't quite understand.

This is not a support channel as mentioned above so please refrain from posting hwre. (You need to wait for a home assistant release or rollback to last months build. This pr has not been released yet. )

**Pull request merged**
